<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Markdown\Markdown.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="8.8.0" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
      <PackageReference Include="NUnit" Version="4.4.0" />
      <PackageReference Include="xunit" Version="2.9.3" />
    </ItemGroup>

</Project>
