//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markdown.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Markdown.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _AAA_ __aaaa__, aa_a_aaa _aa_ ___aaaaaaaa___ aaaaaaaaaaaaaa_ _a_a_  __a __a _aa a_ aaaa__ aaa.
        ///_AAA_ __aaaa__, aa_a_aaa _aa_ ___aaaaaaaa___ aaaaaaaaaaaaaa_ _a_a_  __a __a _aa a_ aaaa__ aaa.
        ///_AAA_ __aaaa__, aa_a_aaa _aa_ ___aaaaaaaa___ aaaaaaaaaaaaaa_ _a_a_  __a __a _aa a_ aaaa__ aaa.
        ///_AAA_ __aaaa__, aa_a_aaa _aa_ ___aaaaaaaa___ aaaaaaaaaaaaaa_ _a_a_  __a __a _aa a_ aaaa__ aaa.
        ///_AAA_ __aaaa__, aa_a_aaa _aa_ ___aaaaaaaa___ aaaaaaaaaaaaaa_ _a_a_  __a __a _aa a_ aaaa__ aaa.
        ///_AAA_ __aaaa__, aa_a_aaa _aa_ __ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string FastTest {
            get {
                return ResourceManager.GetString("FastTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;em&gt;AAA&lt;/em&gt; &lt;strong&gt;aaaa&lt;/strong&gt;, aa_a_aaa &lt;em&gt;aa&lt;/em&gt; &lt;strong&gt;&lt;em&gt;aaaaaaaa&lt;/em&gt;&lt;/strong&gt; aaaaaaaaaaaaaa_ &lt;em&gt;a_a&lt;/em&gt;  &lt;strong&gt;a __a &lt;em&gt;aa a&lt;/em&gt; aaaa&lt;/strong&gt; aaa.
        ///&lt;em&gt;AAA&lt;/em&gt; &lt;strong&gt;aaaa&lt;/strong&gt;, aa_a_aaa &lt;em&gt;aa&lt;/em&gt; &lt;strong&gt;&lt;em&gt;aaaaaaaa&lt;/em&gt;&lt;/strong&gt; aaaaaaaaaaaaaa_ &lt;em&gt;a_a&lt;/em&gt;  &lt;strong&gt;a __a &lt;em&gt;aa a&lt;/em&gt; aaaa&lt;/strong&gt; aaa.
        ///&lt;em&gt;AAA&lt;/em&gt; &lt;strong&gt;aaaa&lt;/strong&gt;, aa_a_aaa &lt;em&gt;aa&lt;/em&gt; &lt;strong&gt;&lt;em&gt;aaaaaaaa&lt;/em&gt;&lt;/strong&gt; aaaaaaaaaaaaaa_ &lt;em&gt;a_a&lt;/em&gt;  &lt;strong&gt;a __a &lt;em&gt;aa a&lt;/em&gt; aaaa&lt;/strong&gt; aaa.
        ///&lt;e [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string FastTestResult {
            get {
                return ResourceManager.GetString("FastTestResult", resourceCulture);
            }
        }
    }
}
