//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markdown.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Markdown.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на M_rkdown: Synt_x
        ///================
        ///
        ///&lt;ul id=&quot;ProjectSubmenu&quot;&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/&quot; title=&quot;M_rkdown Project P_ge&quot;&gt;M_in&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/b_sics&quot; title=&quot;M_rkdown B_sics&quot;&gt;B_sics&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ cl_ss=&quot;selected&quot; title=&quot;M_rkdown Synt_x Document_tion&quot;&gt;Synt_x&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/license&quot; title=&quot;Pricing _nd License In__orm_tion&quot;&gt;License&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/dingus&quot; title=&quot;Online M_rkdown Web Form&quot;&gt;Dingus&lt;/_&gt;&lt;/li&gt;
        ///&lt;/ul [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string markdown_test_file_avg {
            get {
                return ResourceManager.GetString("markdown_test_file_avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на M_rkdown: Synt_x
        ///================
        ///
        ///&lt;ul id=&quot;ProjectSubmenu&quot;&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/&quot; title=&quot;M_rkdown Project P_ge&quot;&gt;M_in&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/b_sics&quot; title=&quot;M_rkdown B_sics&quot;&gt;B_sics&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ cl_ss=&quot;selected&quot; title=&quot;M_rkdown Synt_x Document_tion&quot;&gt;Synt_x&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/license&quot; title=&quot;Pricing _nd License In__orm_tion&quot;&gt;License&lt;/_&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;_ _re__=&quot;/projects/m_rkdown/dingus&quot; title=&quot;Online M_rkdown Web Form&quot;&gt;Dingus&lt;/_&gt;&lt;/li&gt;
        ///&lt;/ul [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string markdown_test_file_big {
            get {
                return ResourceManager.GetString("markdown_test_file_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string MarkdownTestData {
            get {
                return ResourceManager.GetString("MarkdownTestData", resourceCulture);
            }
        }
    }
}
